### ISSUE TITLE
Warning message: 'layout' objects don't have these attributes: 'NA'

### ISSUE THREAD

**Issue by nourelhoda-bouslah** [paulgovan/WeibullR.plotly#2]
Hello,
When I run the code I get the following warning :
Warning message:
'layout' objects don't have these attributes: 'NA'
Valid attributes include:
'_deprecated', 'activeshape', 'annotations', 'autosize', 'autotypenumbers', 'calendar', 'clickmode', 'coloraxis', 'colorscale', 'colorway', 'computed', 'datarevision', 'dragmode', 'editrevision', 'editType', 'font', 'geo', 'grid', 'height', 'hidesources', 'hoverdistance', 'hoverlabel', 'hovermode', 'images', 'legend', 'mapbox', 'margin', 'meta', 'metasrc', 'modebar', 'newshape', 'paper_bgcolor', 'plot_bgcolor', 'polar', 'scene', 'selectdirection', 'selectionrevision', 'separators', 'shapes', 'showlegend', 'sliders', 'smith', 'spikedistance', 'template', 'ternary', 'title', 'transition', 'uirevision', 'uniformtext', 'updatemenus', 'width', 'xaxis', 'yaxis', 'barmode', 'bargap', 'mapType'

I don't know if it's related to the version of plotly or not but I wanted to know if it is for you or not. Because I'm developing an application and I can't continue with the warning.

**Comment by paulgovan** [comment]
Yes, I'm aware of the warning and it has to do with NA values in the table of results. Adding `suspplot = TRUE, restab = FALSE` to the `plotly_wblr` call should remove the warning. Will update once I have a fix.

**Comment by paulgovan** [comment]
This was due to an open issue with plotly: https://github.com/plotly/plotly.R/issues/994.

I created a workaround that's available in the development version:

`
devtools::install_github('paulgovan/weibullr.plotly')
`

**Comment by nourelhoda-bouslah** [comment]
Thank you @paulgovan for your reactivity. It is OK (I will close this issue)
